Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202510.26.0"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  nodes = [
    { name: "k8s-master",   ip: "192.168.57.10", memory: 4096 },
    { name: "k8s-worker-1", ip: "192.168.57.11", memory: 2048 },
    { name: "k8s-worker-2", ip: "192.168.57.12", memory: 2048 },
    { name: "k8s-worker-3", ip: "192.168.57.13", memory: 2048 },
    { name: "k8s-worker-4", ip: "192.168.57.14", memory: 2048 }
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |machine|
      machine.vm.hostname = node[:name]

      machine.vm.provision "shell",
        path: "scripts/prepare-nodes.sh",
        privileged: true

      machine.vm.provision "shell",
        path: "scripts/install-containerd.sh",
        privileged: true

      machine.vm.provision "shell",
        name: "install-kubernetes",
        path: "scripts/install-kubernetes.sh",
        privileged: true

      machine.vm.provision "shell",
        name: "configure-kubelet",
        path: "scripts/configure-kubelet.sh",
        privileged: true
          
      machine.vm.network "private_network",
        ip: node[:ip],
        virtualbox__intnet: false,
        name: "VirtualBox Host-Only Ethernet Adapter #2"

      machine.vm.provider "virtualbox" do |vb|
        vb.name = node[:name]
        vb.memory = node[:memory]
        vb.cpus = 2
        vb.customize [
          "modifyvm", :id,
          "--audio-enabled", "off"
        ]
      end
    end
  end
end
