apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-multitool
spec:
  type: {{ .Values.multitool.service.type }}
  selector:
    app: {{ .Release.Name }}-multitool
  ports:
    - port: {{ .Values.multitool.service.port }}
      targetPort: {{ .Values.multitool.service.port }}
      protocol: TCP
